[bindings.swift]
module_name = "MultiplexReplicationSecurity"
ffi_module_name = "MultiplexReplicationSecurityFFI"
generate_module_map = true

[bindings.kotlin]
package_name = "com.multiplex.replication.security"
cdylib_name = "multiplex_replication_bindings"
generate_immutable_records = true
android = true
kotlin_target_version = "2.1.0"
